version: "3.8"
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile-django
    env_file:
      - .env
    restart: always
    volumes:
      - .:/usr/src/app
      - ./staticfiles:/usr/src/app/staticfiles
      - ./media:/usr/src/app/media
    ports:
      - 8000
    networks:
      - dokploy-network

  realtime:
    build: ./realtime
    env_file:
      - .env
    volumes:
      - ./realtime:/usr/src/realtime
    ports:
      - 8000
    networks:
      - dokploy-network

  celery_scrapy_worker:
    build:
      context: .
      dockerfile: Dockerfile-celery
    command: celery -A dj worker -l INFO -n scrapy_worker -Q scrapy -E --concurrency=5
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - ./staticfiles:/usr/src/app/staticfiles
      - ./media:/usr/src/app/media
    networks:
      - dokploy-network

  celery_orm_worker:
    build:
      context: .
      dockerfile: Dockerfile-celery
    command: celery -A dj worker -l INFO -n orm_worker -Q orm -E --concurrency=16
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - ./staticfiles:/usr/src/app/staticfiles
      - ./media:/usr/src/app/media
    networks:
      - dokploy-network

  celery_download_images_worker:
    build:
      context: .
      dockerfile: Dockerfile-celery
    command: celery -A dj worker -l INFO -n download_images_worker -Q download_images -E --concurrency=4
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - ./staticfiles:/usr/src/app/staticfiles
      - ./media:/usr/src/app/media
    networks:
      - dokploy-network

  celery_email_worker:
    build:
      context: .
      dockerfile: Dockerfile-celery
    command: celery -A dj worker -l INFO -n email_worker -Q email -E --concurrency=2
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - ./staticfiles:/usr/src/app/staticfiles
      - ./media:/usr/src/app/media
    networks:
      - dokploy-network

  celerybeat:
    build:
      context: .
      dockerfile: Dockerfile-celery
    command: ./wait-for-it.sh celery -A dj beat --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - ./staticfiles:/usr/src/app/staticfiles
      - ./media:/usr/src/app/media
    networks:
      - dokploy-network

  nginx:
    build: ./nginx
    volumes:
      - ./staticfiles:/usr/src/app/staticfiles
      - ./media:/usr/src/app/media
      - ./frontend:/usr/src/app/frontend
    ports:
      - 80
    depends_on:
      - django
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.django.rule=Host(`itab.ltd`)
      - traefik.http.routers.django.entrypoints=websecure
      - traefik.http.routers.django.tls.certResolver=letsencrypt
      - traefik.http.services.django.loadbalancer.server.port=80
      - traefik.http.middlewares.no-compression.compress.enabled=false
      - traefik.http.middlewares.custom-timeout.responseTimeout=30s
      - traefik.http.middlewares.custom-timeout.idleTimeout=10s
      - traefik.http.middlewares.custom-timeout.requestTimeout=60s
networks:
  dokploy-network:
    external: true
