FROM python:3.11

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN adduser --disabled-password --gecos '' mhmd

RUN chown -R mhmd:mhmd /usr/src/app

RUN apt-get update && apt-get install -y \
    postgresql-client \
    build-essential \
    libffi-dev \
    python3-dev \
    graphviz libgraphviz-dev pkg-config\
    gcc \
    gfortran \
    libopenblas-dev \
    liblapack-dev && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install spacy \
    && python -m spacy download en_core_web_sm \
    && python -m nltk.downloader stopwords \
    && python -m nltk.downloader wordnet

COPY . .

# EXPOSE 8000

# ADD docker-entrypoint.sh /docker-entrypoint.sh
# RUN chmod +x /docker-entrypoint.sh
# ENTRYPOINT ["/docker-entrypoint.sh"]

# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
# CMD ["gunicorn",  "--config", "dj/gunicorn.conf.py", "dj.wsgi:application", "--bind", "0.0.0.0:8000", "--capture-output", "--enable-stdio-inheritance", "--workers", "4"]
