version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: savvy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: "redis:alpine"

  django:
    build: .
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    # user: "1000:1000"
    command: pipenv run celery -A dj worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celerybeat:
    build: .
    command: pipenv run celery -A dj beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
      - redis

  # flower:
  #   image: mher/flower
  #   command: flower --broker=redis://redis:6379/0
  #   ports:
  #     - "5555:5555"
  #   depends_on:
  #     - redis

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

    ports:
      - "9090:9090"
    depends_on:
      - django # or any other service you want to monitor

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

networks:
  default:
    driver: bridge

volumes:
  grafana_data:
  prometheus_data:

