version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - djangonetwork

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    networks:
      - djangonetwork

  django:
    # restart: always
    build: .
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - ./staticfiles:/usr/src/app/staticfiles
      - ./media:/usr/src/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis
    networks:
      - djangonetwork

  realtime:
    build: ./realtime
    expose:
      - 8001
    env_file:
      - .env
    volumes:
      - ./realtime:/usr/src/realtime
    ports:
      - "8001:8000" # Expose the service on host port 8001 and container port 8000
    depends_on:
      - redis
    links:
      - redis:redis
    networks:
      - djangonetwork

  celery_scrapy_worker:
    build: .
    command: celery -A dj worker -l INFO -n scrapy_worker -Q scrapy -E --concurrency=5
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - ./staticfiles:/usr/src/app/staticfiles
      - ./media:/usr/src/app/media
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis
    networks:
      - djangonetwork

  celery_orm_worker:
    build: .
    command: celery -A dj worker -l INFO -n orm_worker -Q orm -E --concurrency=16
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - ./staticfiles:/usr/src/app/staticfiles
      - ./media:/usr/src/app/media
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis
    networks:
      - djangonetwork

  celery_download_images_worker:
    build: .
    command: celery -A dj worker -l INFO -n download_images_worker -Q download_images -E --concurrency=4
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - ./staticfiles:/usr/src/app/staticfiles
      - ./media:/usr/src/app/media
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis
    networks:
      - djangonetwork

  celery_email_worker:
    build: .
    command: celery -A dj worker -l INFO -n email_worker -Q email -E --concurrency=2
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - ./staticfiles:/usr/src/app/staticfiles
      - ./media:/usr/src/app/media
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis
    networks:
      - djangonetwork

  celerybeat:
    build: .
    command: celery -A dj beat --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - ./staticfiles:/usr/src/app/staticfiles
      - ./media:/usr/src/app/media
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis
    networks:
      - djangonetwork

  nginx:
    build: ./nginx
    volumes:
      - ./staticfiles:/usr/src/app/staticfiles
      - ./media:/usr/src/app/media
      - ./frontend:/usr/src/app/frontend
    ports:
      - "80:80"
    depends_on:
      - django
    networks:
      - djangonetwork

networks:
  default:
    driver: bridge
  djangonetwork:
    driver: bridge

volumes:
  grafana_data:
  prometheus_data:
  redis_data:
