# Generated by Django 4.2.7 on 2023-11-11 05:49

import common.utils.model_utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_clustertag_name_alter_documentwordweight_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkfile',
            name='tasks',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='scrapyresponselog',
            name='html_file',
            field=models.FileField(blank=True, null=True, upload_to='scrape/html/', validators=[django.core.validators.FileExtensionValidator(['html']), common.utils.model_utils.FileSizeValidator(5)]),
        ),
    ]
