# Generated by Django 4.2.7 on 2023-12-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0009_tag_rename_document_documentwordweight_bookmark_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="title",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
