# Generated by Django 4.2.7 on 2023-12-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_bookmark_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentwordweight',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
