# Generated by Django 4.2.7 on 2023-12-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0012_documentwordweight_important"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmarkwebpage",
            name="url",
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name="scrapyresponselog",
            name="url",
            field=models.URLField(max_length=2048),
        ),
    ]
