# Generated by Django 4.2.9 on 2024-01-16 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0015_alter_tag_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkfile',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bookmarkfile',
            unique_together={('user', 'file_hash')},
        ),
    ]
