# Generated by Django 4.2.9 on 2024-01-27 02:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0019_bookmark_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentCluster',
            new_name='Cluster',
        ),
    ]
