# Generated by Django 4.2.9 on 2024-02-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0023_bookmarkfile_failed_links_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="image_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
