# Generated by Django 4.2.9 on 2024-02-08 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0024_bookmark_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookmarkwebpage",
            name="url",
        ),
        migrations.RemoveField(
            model_name="scrapyresponselog",
            name="url",
        ),
        migrations.AlterField(
            model_name="bookmarkwebpage",
            name="bookmark",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webpages",
                to="App.bookmark",
            ),
        ),
        migrations.AlterField(
            model_name="scrapyresponselog",
            name="bookmark",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scrapes",
                to="App.bookmark",
            ),
        ),
    ]
