# Generated by Django 4.2.9 on 2024-02-12 19:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0025_remove_bookmarkwebpage_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='similarity_calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SimilarityMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='similarity-matrix/', validators=[django.core.validators.FileExtensionValidator(['json'])])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_matrix', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
