# Generated by Django 4.2.9 on 2024-02-16 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_bookmark_similarity_calculated_similaritymatrix'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentWordWeight',
            new_name='WordWeight',
        ),
    ]
