# Generated by Django 4.2.9 on 2024-02-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_rename_documentwordweight_wordweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='cloned',
            field=models.BooleanField(default=False),
        ),
    ]
