# Generated by Django 4.2.7 on 2024-04-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0030_cluster_bookmarks_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="similaritymatrix",
            name="bookmarks_ids",
            field=models.JSONField(default=list),
        ),
    ]
