# Generated by Django 4.2.7 on 2024-04-23 04:29

import uuid

from django.db import migrations, models


def create_uuid(apps, schema_editor):
    Bookmark = apps.get_model("App", "Bookmark")
    for bookmark in Bookmark.objects.all():
        bookmark.uuid = uuid.uuid4()
        bookmark.save()


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0032_cluster_tags_alter_similaritymatrix_bookmarks_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name="bookmark",
            name="uuid",
            field=models.UUIDField(
                db_index=True, editable=False, default=uuid.uuid4, unique=True
            ),
        ),
    ]
