# Generated by Django 4.2.7 on 2024-04-20 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0032_cluster_tags_alter_similaritymatrix_bookmarks_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordGraphNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarks_count', models.PositiveSmallIntegerField(default=0)),
                ('path', models.CharField(blank=True, db_index=True, max_length=1024, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='nodes', to='App.bookmark')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='App.wordgraphnode')),
                ('tags', models.ManyToManyField(blank=True, related_name='nodes', to='App.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
