# Generated by Django 4.2.7 on 2024-04-23 04:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_bookmark_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='BookmarkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='App.bookmark')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
