# Generated by Django 4.2.7 on 2024-04-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_wordgraphnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordgraphnode',
            name='is_leaf',
            field=models.BooleanField(default=False),
        ),
    ]
