# Generated by Django 4.2.7 on 2024-05-01 18:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("App", "0034_wordgraphnode_is_leaf"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WordGraphNode",
            new_name="GraphNode",
        ),
    ]
