# Generated by Django 4.2.7 on 2024-05-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0035_rename_wordgraphnode_graphnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphnode',
            name='similarity_matrix',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
