# Generated by Django 4.2.7 on 2024-05-07 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_alter_bookmark_uuid_bookmarkhistory'),
        ('App', '0036_graphnode_similarity_matrix'),
    ]

    operations = [
    ]
