# Generated by Django 4.2.7 on 2024-05-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_website_bookmark_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphnode',
            name='is_sharded_islands',
            field=models.BooleanField(default=False),
        ),
    ]
