# Generated by Django 4.2.7 on 2024-06-02 04:52

import django.core.validators
from django.db import migrations, models

import common.utils.model_utils


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0041_remove_bookmark_user_status_bookmark_added_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmarkfile",
            name="location",
            field=models.FileField(
                upload_to="users/bookmarks/",
                validators=[
                    django.core.validators.FileExtensionValidator(["html", "json"]),
                    common.utils.model_utils.FileSizeValidator(20),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="wordweight",
            name="word",
            field=models.CharField(db_index=True, max_length=2048),
        ),
    ]
