# Generated by Django 4.2.7 on 2024-06-06 01:48

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0043_alter_wordweight_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
