# Generated by Django 4.2.7 on 2024-07-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0046_tag_bookmarks_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphnode',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
