# Generated by Django 4.2.7 on 2024-08-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0047_graphnode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
