# Generated by Django 4.2.7 on 2024-10-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0048_alter_tag_weight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wordweight",
            name="bookmark",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="alias_name",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="weight",
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="process_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (None, None),
                    (10, "created"),
                    (20, "cloned from another user bookmark (to status 60)"),
                    (30, "sent to scrapy crawler"),
                    (35, "crawled failed for any reason"),
                    (40, "crawled succeeded"),
                    (50, "start text processing"),
                    (60, "text processed"),
                ],
                default=10,
            ),
        ),
        migrations.DeleteModel(
            name="GraphNode",
        ),
        migrations.DeleteModel(
            name="WordWeight",
        ),
    ]
