from rest_framework.routers import DefaultRouter, Route


class CustomSuffixRouter(DefaultRouter):
    def get_routes(self, viewset):
        """
        Return a list of `Route` instances for the given viewset.
        """
        # Get the default routes generated by the parent class
        routes = super().get_routes(viewset)

        # Create custom routes for create and list actions
        create_route = Route(
            url=r'^{prefix}/create{trailing_slash}$',
            mapping={'post': 'create'},
            name='{basename}-create',
            detail=False,
            initkwargs={},
        )
        list_route = Route(
            url=r'^{prefix}/list{trailing_slash}$',
            mapping={'get': 'list'},
            name='{basename}-list',
            detail=False,
            initkwargs={},
        )

        # Append the custom routes to the default routes
        routes = [create_route, list_route] + routes
        return routes
